# Generated by Django 5.1.4 on 2025-04-09 12:10

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Candidate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("contact", models.CharField(max_length=15)),
                ("mail_id", models.EmailField(max_length=254)),
                ("gender", models.CharField(max_length=10)),
                ("experience", models.CharField(max_length=50)),
                ("role", models.CharField(max_length=50)),
            ],
        ),
    ]
