# Generated by Django 5.1.4 on 2025-04-09 12:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("interviews", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="candidate",
            name="experience",
            field=models.CharField(max_length=100),
        ),
    ]
