# Generated by Django 5.1.4 on 2025-04-09 12:49

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("interviews", "0002_alter_candidate_experience"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Candidate",
            new_name="Telecaller",
        ),
    ]
