# Generated by Django 5.1.4 on 2025-04-11 09:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("interviews", "0003_rename_candidate_telecaller"),
    ]

    operations = [
        migrations.CreateModel(
            name="Counselor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("contact", models.CharField(max_length=15)),
                ("mail_id", models.EmailField(max_length=254)),
                ("gender", models.CharField(max_length=10)),
                ("experience", models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name="telecaller",
            name="role",
        ),
    ]
