# Generated by Django 5.1.4 on 2025-04-12 06:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("interviews", "0005_schedule"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="schedule",
            name="candidate",
        ),
        migrations.AddField(
            model_name="schedule",
            name="content_type",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="contenttypes.contenttype",
            ),
        ),
        migrations.AddField(
            model_name="schedule",
            name="object_id",
            field=models.PositiveIntegerField(null=True),
        ),
    ]
